### ISSUE TITLE
Support for borders only in topleft, right etc

### ISSUE THREAD

**Issue by eripe970** [Monksc/cupertino_rounded_corners#1]
Would be nice to be able to create a border with circular curve only on for example top left and top right. 

Example from BorderRadius. 
```
BorderRadius.only(
  topLeft: Radius.circular(10),
  topRight: Radius.circular(10))
)
```

**Comment by Monksc** [comment]
I just updated the library for version 1.1.0. Please tell me what you think and if I can close the issue. I love the idea by the way.

**Comment by eripe970** [comment]
Awesome! 🙌
