### ISSUE TITLE
Upgrade to null safety

### ISSUE THREAD

**Issue by eripe970** [Monksc/cupertino_rounded_corners#3]
Hey, 

I'm about to migrate my apps to null safety, (https://dart.dev/null-safety/migration-guide) any plans in upgrading this library?

**Comment by Monksc** [comment]
I haven't looked at it yet but will in a few weeks. I'll let you know then.

**Comment by Monksc** [comment]
I just updated to null safety.

**Comment by eripe970** [comment]
😍😍😍
