### ISSUE TITLE
Hi - feature request!

### ISSUE THREAD

**Issue by idotalmor** [Monksc/cupertino_rounded_corners#4]
Great package!
maybe gradient option for bg?

Keep the good work!

Thanks:)

**Comment by Monksc** [comment]
Thank you Ido!

Sorry, I did not see this till now. There is a lot I'll like to add when I get the chance to work on it. Like I would like to have the path be public to allow developers to use it for other things. I will also like to add in some other widgets like a Button widget and a Clip Path widget. I will definitely add in a gradient to the background. Any other ideas will be appreciative.

Thanks.

**Comment by Monksc** [comment]
I updated the code to include a gradient in the background. If you could verify this and close with a comment that would be great.

**Comment by Monksc** [comment]
Im going to close this now.
